name: Deploy Palpittero FE to Staging

on: 
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Staging Deployment
    runs-on: ubuntu-latest
    
    env:
      VITE_API_URL: https://staging-api.palpittero.com.br/api
      VITE_API_TIMEOUT: 60000

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/setup-node@master
      - run: npm install && npm run build:staging
      - name: Copy staging dist files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: /var/www/palpittero.com.br/staging
          strip_components: 1
