name: Deploy Palpittero FE to Production

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Production Deployment
    runs-on: ubuntu-latest
    
    env:
      VITE_API_URL: https://api.palpittero.com.br/api
      VITE_API_TIMEOUT: 60000
      VITE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@master
      - run: npm install && npm run build
      - name: Copy production dist files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: /var/www/palpittero.com.br/production
          strip_components: 1
